const suits = [{ name: "hearts", symbol: "♥", color: "red" }, { name: "diamonds", symbol: "♦", color: "red" }, { name: "clubs", symbol: "♣", color: "black" }, { name: "spades", symbol: "♠", color: "black" }];
const ranks = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
const players = [{ name: "You", initial: "Y", hand: [], score: 0, human: true }, { name: "Noa", initial: "N", hand: [], score: 0 }, { name: "Rami", initial: "R", hand: [], score: 0 }, { name: "Tali", initial: "T", hand: [], score: 0 }];
let playerCount = 4, humanCount = 1, drawPile = [], discardPile = [], currentPlayer = 0, phase = "play", selected = [], round = 1, toastTimer, drawableDiscard = 0, handsRevealed = false, gameOver = false, handoffPending = false;
const $ = (id) => document.getElementById(id);
const activePlayers = () => players.slice(0, playerCount);
function makeDeck() { return suits.flatMap((suit) => ranks.map((rank) => ({ suit: suit.name, symbol: suit.symbol, color: suit.color, rank, value: rank === "A" ? 1 : ["J", "Q", "K"].includes(rank) ? 10 : Number(rank) }))); }
function shuffle(cards) { for (let index = cards.length - 1; index > 0; index--) { const swap = Math.floor(Math.random() * (index + 1)); [cards[index], cards[swap]] = [cards[swap], cards[index]]; } return cards; }
function handValue(hand) { return hand.reduce((total, card) => total + card.value, 0); }
const pipPositions = { 1: [[3, 2]], 2: [[1, 1], [5, 3]], 3: [[1, 1], [3, 2], [5, 3]], 4: [[1, 1], [1, 3], [5, 1], [5, 3]], 5: [[1, 1], [1, 3], [3, 2], [5, 1], [5, 3]], 6: [[1, 1], [1, 3], [3, 1], [3, 3], [5, 1], [5, 3]], 7: [[1, 1], [1, 3], [3, 1], [3, 2], [3, 3], [5, 1], [5, 3]], 8: [[1, 1], [1, 3], [2, 1], [2, 3], [4, 1], [4, 3], [5, 1], [5, 3]], 9: [[1, 1], [1, 3], [2, 1], [2, 3], [3, 2], [4, 1], [4, 3], [5, 1], [5, 3]], 10: [[1, 1], [1, 3], [2, 1], [2, 3], [3, 1], [3, 3], [4, 1], [4, 3], [5, 1], [5, 3]] };
function cardHTML(card, corner = true) { const count = Number(card.rank); const face = pipPositions[count] ? `<span class="pips pips-${count}">${pipPositions[count].map(([row, column]) => `<span style="grid-row: ${row}; grid-column: ${column}">${card.symbol}</span>`).join("")}</span>` : `<span class="face-symbol">${card.symbol}</span>`; return `<div class="card-face ${card.color}">${corner ? `<span class="card-corner">${card.rank}<br><span>${card.symbol}</span></span>` : ""}${face}</div>`; }
function startRound() { gameOver = false; drawPile = shuffle(makeDeck()); discardPile = [drawPile.pop()]; players.forEach((player) => { player.hand = []; }); activePlayers().forEach((player) => { player.hand = drawPile.splice(0, 5); }); currentPlayer = 0; phase = "play"; selected = []; drawableDiscard = 0; handsRevealed = false; handoffPending = false; render(); }
function render() { renderScores(); renderOpponents(); renderHand(); $("discard-card").innerHTML = cardHTML(discardPile[discardPile.length - 1]); $("draw-count").textContent = drawPile.length; const current = players[currentPlayer]; const playDisabled = gameOver || handoffPending || !current.human || phase !== "play" || !selected.length || !validPlay(selected); $("round-label").textContent = gameOver ? "GAME OVER" : `ROUND ${String(round).padStart(2, "0")}`; $("turn-label").textContent = gameOver ? "MATCH COMPLETE" : handoffPending ? `PASS TO ${current.name.toUpperCase()}` : current.human ? (phase === "play" ? `${current.name.toUpperCase()}'S TURN` : "DRAW A CARD") : `${current.name.toUpperCase()} IS THINKING`; $("draw-pile").disabled = gameOver || handoffPending || !current.human || phase !== "draw"; $("discard-pile").disabled = gameOver || handoffPending || !current.human || phase !== "draw"; $("yaniv-button").disabled = gameOver || handoffPending || !current.human || phase !== "play" || handValue(current.hand) > 7; $("play-button").disabled = playDisabled; $("play-top-button").disabled = playDisabled; $("hand-points").textContent = `${handValue(players[0].hand)} PTS`; }
function renderScores() { $("score-list").innerHTML = activePlayers().map((player) => `<div class="score-row"><div class="avatar">${player.initial}</div><div class="score-name">${player.name}<small>${player.human ? "human seat" : "CPU player"}</small></div><div class="score-value">${player.score}</div></div>`).join(""); }
function renderOpponents() { $("opponents").innerHTML = activePlayers().slice(1).map((player, index) => `<div class="opponent ${currentPlayer === index + 1 ? "active" : ""}"><div class="avatar">${player.initial}</div><strong>${player.name}</strong><div class="card-count">${player.hand.length} CARDS</div></div>`).join(""); }
function renderHand() { const current = players[currentPlayer]; if (!current.human && !handoffPending) { $("player-hand").innerHTML = `<div class="handoff"><strong>${current.name} is playing</strong><span>Their hand is hidden.</span></div>`; $("selection-info").textContent = "Waiting for the next turn"; return; } if (handoffPending) { $("player-hand").innerHTML = `<div class="handoff"><strong>Pass the device to ${current.name}</strong><span>The previous hand is hidden.</span><button type="button" class="primary-button" id="ready-button">I am ready</button></div>`; $("selection-info").textContent = "Hand hidden until the next player is ready"; $("ready-button").addEventListener("click", () => { handoffPending = false; render(); }); return; } $("player-hand").innerHTML = current.hand.map((card, index) => `<button type="button" class="card-button ${selected.includes(index) ? "selected" : ""}" data-index="${index}" aria-label="${card.rank} of ${card.suit}">${cardHTML(card)}</button>`).join(""); document.querySelectorAll(".card-button").forEach((button) => button.addEventListener("click", () => toggleCard(Number(button.dataset.index)))); $("selection-info").textContent = selected.length ? `${selected.length} selected${validPlay(selected) ? " - legal play" : " - not a legal play"}` : "Select a card or meld"; }
function toggleCard(index) { if (phase !== "play") return; selected = selected.includes(index) ? selected.filter((item) => item !== index) : [...selected, index]; render(); }
function validPlay(indexes) { const cards = indexes.map((index) => players[currentPlayer].hand[index]); if (!cards.length) return false; if (cards.length === 1) return true; if (cards.every((card) => card.rank === cards[0].rank)) return true; if (cards.length < 3 || !cards.every((card) => card.suit === cards[0].suit)) return false; const values = cards.map((card) => card.rank === "A" ? 1 : ranks.indexOf(card.rank) + 1).sort((a, b) => a - b); return values.every((value, index) => index === 0 || value === values[index - 1] + 1); }
function playHuman() { if (!players[currentPlayer].human || !validPlay(selected)) return; drawableDiscard = discardPile.length - 1; const cards = selected.sort((a, b) => b - a).map((index) => players[currentPlayer].hand.splice(index, 1)[0]); discardPile.push(...cards); selected = []; phase = "draw"; message(`Played ${cards.length === 1 ? "a card" : `${cards.length} cards`}. Draw exactly one card.`); render(); }
function recycleDiscard() { if (drawPile.length || discardPile.length < 2) return; const topCard = discardPile.pop(); drawPile = shuffle(discardPile); discardPile = [topCard]; }
function drawFromDeck() { recycleDiscard(); return drawPile.pop(); }
function drawHuman(fromDiscard) { if (phase !== "draw" || !players[currentPlayer].human) return; players[currentPlayer].hand.push(fromDiscard ? discardPile.splice(drawableDiscard, 1)[0] : drawFromDeck()); phase = "play"; advanceTurn(); }
function message(text) { $("table-message").textContent = text; }
function showToast(text) { $("toast").textContent = text; $("toast").classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => $("toast").classList.remove("show"), 2800); }
function callYaniv() { if (phase === "play" && players[currentPlayer].human && handValue(players[currentPlayer].hand) <= 7) scoreRound(currentPlayer); }
function scoreRound(caller) { const table = activePlayers(); const values = table.map((player) => handValue(player.hand)); const lowest = Math.min(...values); const callerSuccessful = values[caller] === lowest && values.filter((value) => value === lowest).length === 1; table.forEach((player, index) => { if (index === caller) player.score += callerSuccessful ? 0 : 30; else if (values[index] !== lowest) player.score += values[index]; }); const loser = table.find((player) => player.score >= 100); render(); showToast(callerSuccessful ? `${table[caller].name} called Yaniv and scored 0.` : `${table[caller].name} got caught. +30 points.`); if (loser) { const winner = [...table].sort((a, b) => a.score - b.score)[0]; gameOver = true; render(); setTimeout(() => showToast(`${winner.name} wins the table with ${winner.score} points.`), 3000); return; } round++; setTimeout(startRound, 1500); }
function chooseAIPlay(player) { let highestIndex = 0; player.hand.forEach((card, index) => { if (card.value > player.hand[highestIndex].value) highestIndex = index; }); return [highestIndex]; }
function advanceTurn() { currentPlayer = (currentPlayer + 1) % playerCount; selected = []; handoffPending = humanCount > 1 && players[currentPlayer].human; message("The table is moving."); render(); if (!handoffPending) setTimeout(runAI, 500); }
function runAI() { if (gameOver || currentPlayer === 0 && players[currentPlayer].human) return; const player = players[currentPlayer]; if (handValue(player.hand) <= 7) { scoreRound(currentPlayer); return; } const cards = chooseAIPlay(player).sort((a, b) => b - a).map((index) => player.hand.splice(index, 1)[0]); discardPile.push(...cards); const fromDiscard = discardPile[discardPile.length - 2].value < 6; player.hand.push(fromDiscard ? discardPile.splice(discardPile.length - 2, 1)[0] : drawFromDeck()); advanceTurn(); }
function dealHand() { if (!gameOver) { startRound(); message("A fresh hand has been dealt."); } }
function newGame() { $("setup-dialog").showModal(); }
function startGame() { playerCount = Number($("player-count").value); humanCount = Math.min(Number($("human-count").value), playerCount); players.forEach((player, index) => { player.score = 0; player.human = index < humanCount; }); round = 1; $("setup-dialog").close(); startRound(); message("Your turn. Play a card or call Yaniv."); }
$("human-count").addEventListener("change", () => { $("human-count").value = Math.min(Number($("human-count").value), Number($("player-count").value)); }); $("player-count").addEventListener("change", () => { $("human-count").value = Math.min(Number($("human-count").value), Number($("player-count").value)); }); $("play-button").addEventListener("click", playHuman); $("play-top-button").addEventListener("click", playHuman); $("draw-pile").addEventListener("click", () => drawHuman(false)); $("discard-pile").addEventListener("click", () => drawHuman(true)); $("yaniv-button").addEventListener("click", callYaniv); $("new-game-button").addEventListener("click", newGame); $("deal-button").addEventListener("click", dealHand); $("start-game-button").addEventListener("click", startGame); $("rules-button").addEventListener("click", () => $("rules-dialog").showModal()); $("close-rules").addEventListener("click", () => $("rules-dialog").close()); startRound();
