const suits = [{ name: "hearts", symbol: "♥", color: "red" }, { name: "diamonds", symbol: "♦", color: "red" }, { name: "clubs", symbol: "♣", color: "black" }, { name: "spades", symbol: "♠", color: "black" }];
const ranks = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
const players = [{ name: "You", initial: "Y", hand: [], score: 0, human: true }, { name: "Noa", initial: "N", hand: [], score: 0 }, { name: "Rami", initial: "R", hand: [], score: 0 }, { name: "Tali", initial: "T", hand: [], score: 0 }];
let playerCount = 4, humanCount = 1, drawPile = [], discardPile = [], currentPlayer = 0, nextRoundStarter = 0, phase = "play", selected = [], round = 1, toastTimer, drawableDiscard = 0, handsRevealed = false, gameOver = false, handoffPending = false, actionPending = false;
const $ = (id) => document.getElementById(id);
const activePlayers = () => players.slice(0, playerCount);
function makeDeck() { return suits.flatMap((suit) => ranks.map((rank) => ({ suit: suit.name, symbol: suit.symbol, color: suit.color, rank, value: rank === "A" ? 1 : ["J", "Q", "K"].includes(rank) ? 10 : Number(rank) }))); }
function shuffle(cards) { for (let index = cards.length - 1; index > 0; index--) { const swap = Math.floor(Math.random() * (index + 1)); [cards[index], cards[swap]] = [cards[swap], cards[index]]; } return cards; }
function handValue(hand) { return hand.reduce((total, card) => total + card.value, 0); }
function straightValue(card) { return card.rank === "A" ? 1 : ranks.indexOf(card.rank) + 1; }
const pipPositions = { 1: [[3, 2]], 2: [[1, 1], [5, 3]], 3: [[1, 1], [3, 2], [5, 3]], 4: [[1, 1], [1, 3], [5, 1], [5, 3]], 5: [[1, 1], [1, 3], [3, 2], [5, 1], [5, 3]], 6: [[1, 1], [1, 3], [3, 1], [3, 3], [5, 1], [5, 3]], 7: [[1, 1], [1, 3], [3, 1], [3, 2], [3, 3], [5, 1], [5, 3]], 8: [[1, 1], [1, 3], [2, 1], [2, 3], [4, 1], [4, 3], [5, 1], [5, 3]], 9: [[1, 1], [1, 3], [2, 1], [2, 3], [3, 2], [4, 1], [4, 3], [5, 1], [5, 3]], 10: [[1, 1], [1, 3], [2, 1], [2, 3], [3, 1], [3, 3], [4, 1], [4, 3], [5, 1], [5, 3]] };
function cardHTML(card, corner = true) { const count = Number(card.rank); const isCourt = ["J", "Q", "K"].includes(card.rank); const face = card.rank === "A" && card.suit === "spades" ? `<span class="ace-emblem"><span class="ace-ornament">✦</span><strong>♠</strong><span class="ace-ornament">✦</span></span>` : pipPositions[count] ? `<span class="pips pips-${count}">${pipPositions[count].map(([row, column]) => `<span style="grid-row: ${row}; grid-column: ${column}">${card.symbol}</span>`).join("")}</span>` : isCourt ? `<span class="court-art court-${card.rank.toLowerCase()}"><span class="court-crown">♛</span><strong>${card.rank}</strong><span class="court-suit">${card.symbol}</span><span class="court-crown">♛</span></span>` : `<span class="face-symbol">${card.symbol}</span>`; return `<div class="card-face ${card.color} ${card.rank === "A" && card.suit === "spades" ? "ace-spades" : ""} ${isCourt ? "court-card" : ""}">${corner ? `<span class="card-corner">${card.rank}<br><span>${card.symbol}</span></span>${isCourt ? `<span class="card-corner bottom-corner">${card.rank}<br><span>${card.symbol}</span></span>` : ""}` : ""}${face}</div>`; }
function startRound() { gameOver = false; drawPile = shuffle(makeDeck()); discardPile = [drawPile.pop()]; players.forEach((player) => { player.hand = []; }); activePlayers().forEach((player) => { player.hand = drawPile.splice(0, 5); }); currentPlayer = nextRoundStarter; nextRoundStarter = 0; phase = "play"; selected = []; drawableDiscard = 0; handsRevealed = false; handoffPending = false; render(); $("discard-card").classList.add("deal-face-down"); animateShuffle(() => animateDeal(() => { if (!players[currentPlayer].human) setTimeout(runAI, 500); })); }
function animateShuffle(callback) { const deck = $("draw-pile"); const felt = deck.closest(".felt"); const riffleOffsets = [-62, -44, -26, -9, 9, 26, 44, 62]; const animation = document.createElement("span"); animation.className = "shuffle-animation"; animation.setAttribute("aria-hidden", "true"); animation.innerHTML = `<span class="shuffle-packet shuffle-packet-left"></span><span class="shuffle-packet shuffle-packet-right"></span><span class="shuffle-riffle">${riffleOffsets.map((offset, index) => `<span style="--riffle-offset: ${offset}px; --riffle-index: ${index}"></span>`).join("")}</span><span class="shuffle-square"></span><span class="shuffle-bridge"></span>`; felt.classList.add("shuffling-felt"); deck.classList.add("shuffling-deck"); felt.appendChild(animation); animation.addEventListener("animationend", (event) => { if (event.target !== animation) return; animation.remove(); felt.classList.remove("shuffling-felt"); deck.classList.remove("shuffling-deck"); callback(); }, { once: true }); }
function animateDeal(callback) { const deck = $("draw-pile"); const deckRect = deck.getBoundingClientRect(); const destinations = [...document.querySelectorAll(".opponent"), $("player-hand")]; const cards = []; destinations.forEach((destination, destinationIndex) => { if (!destination) return; const target = destination.getBoundingClientRect(); for (let cardIndex = 0; cardIndex < 5; cardIndex += 1) { const flight = document.createElement("span"); flight.className = "deal-card-flight"; flight.style.left = `${deckRect.width / 2 - 29}px`; flight.style.top = `${deckRect.height / 2 - 40}px`; flight.style.setProperty("--deal-x", `${target.left + target.width / 2 - (deckRect.left + deckRect.width / 2)}px`); flight.style.setProperty("--deal-y", `${target.top + target.height / 2 - (deckRect.top + deckRect.height / 2)}px`); flight.style.setProperty("--deal-delay", `${(destinationIndex * 5 + cardIndex) * 65}ms`); deck.appendChild(flight); cards.push(flight); } }); $("player-hand").classList.add("dealing"); $("discard-card").classList.add("deal-face-down"); const lastCard = cards[cards.length - 1]; if (!lastCard) { finishDeal(callback); return; } lastCard.addEventListener("animationend", () => finishDeal(callback), { once: true }); }
function finishDeal(callback) { document.querySelectorAll(".deal-card-flight").forEach((card) => card.remove()); $("player-hand").classList.remove("dealing"); $("discard-card").classList.remove("deal-face-down"); $("discard-card").classList.add("deal-face-up"); $("discard-card").addEventListener("animationend", () => { $("discard-card").classList.remove("deal-face-up"); callback(); }, { once: true }); }
function render() { renderScores(); renderOpponents(); renderHand(); $("discard-card").innerHTML = cardHTML(discardPile[discardPile.length - 1]); $("draw-count").textContent = drawPile.length; const current = players[currentPlayer]; const playDisabled = gameOver || handoffPending || !current.human || phase !== "play" || !selected.length || !validPlay(selected); $("round-label").textContent = gameOver ? "GAME OVER" : `ROUND ${String(round).padStart(2, "0")}`; $("turn-label").textContent = gameOver ? "MATCH COMPLETE" : handsRevealed ? "ROUND COMPLETE" : handoffPending ? `PASS TO ${current.name.toUpperCase()}` : current.human ? (phase === "play" ? `${current.name.toUpperCase()}'S TURN` : "DRAW A CARD") : `${current.name.toUpperCase()} IS THINKING`; $("draw-pile").disabled = gameOver || handoffPending || !current.human || phase !== "draw"; $("discard-pile").disabled = gameOver || handoffPending || !current.human || phase !== "draw"; $("yaniv-button").disabled = gameOver || handoffPending || handsRevealed || !current.human || phase !== "play" || handValue(current.hand) > 7; $("deal-button").disabled = !gameOver && !handsRevealed; $("deal-button").textContent = gameOver ? "New game" : "Shuffle"; $("play-top-button").disabled = playDisabled; $("hand-points").textContent = `${handValue(players[0].hand)} PTS`; }
function renderScores() { $("score-list").innerHTML = activePlayers().map((player) => `<div class="score-row"><div class="avatar">${player.initial}</div><div class="score-name">${player.name}<small>${player.human ? "human seat" : "CPU player"}</small></div><div class="score-value">${player.score}</div></div>`).join(""); }
function renderOpponents() { $("opponents").innerHTML = activePlayers().slice(1).map((player, index) => `<div class="opponent ${currentPlayer === index + 1 ? "active" : ""}"><div class="avatar">${player.initial}</div><strong>${player.name}</strong><div class="card-count">${player.hand.length} CARDS</div></div>`).join(""); }
function renderHand() { const current = players[currentPlayer]; if (handsRevealed) { $("player-hand").innerHTML = `<div class="revealed-player-hand">${activePlayers().map((player) => `<div class="revealed-seat"><span class="eyebrow">${player.human ? "Your" : player.name + "'s"} hand</span><div class="revealed-hand">${player.hand.map((card) => cardHTML(card)).join("")}</div></div>`).join("")}</div>`; $("selection-info").textContent = gameOver ? "The match is complete" : "Review the hands, then shuffle for the next round"; return; } if (!current.human && !handoffPending) { $("player-hand").innerHTML = `<div class="handoff"><strong>${current.name} is playing</strong><span>Their hand is hidden.</span></div>`; $("selection-info").textContent = "Waiting for the next turn"; return; } if (handoffPending) { $("player-hand").innerHTML = `<div class="handoff"><strong>Pass the device to ${current.name}</strong><span>The previous hand is hidden.</span><button type="button" class="primary-button" id="ready-button">I am ready</button></div>`; $("selection-info").textContent = "Hand hidden until the next player is ready"; $("ready-button").addEventListener("click", () => { handoffPending = false; render(); }); return; } $("player-hand").innerHTML = current.hand.map((card, index) => `<button type="button" class="card-button ${selected.includes(index) ? "selected" : ""}" data-index="${index}" draggable="true" aria-label="${card.rank} of ${card.suit}">${cardHTML(card)}</button>`).join(""); document.querySelectorAll(".card-button").forEach((button) => { button.addEventListener("click", () => toggleCard(Number(button.dataset.index))); button.addEventListener("dragstart", (event) => { event.dataTransfer.setData("text/plain", button.dataset.index); button.classList.add("dragging"); }); button.addEventListener("dragend", () => button.classList.remove("dragging")); button.addEventListener("dragover", (event) => event.preventDefault()); button.addEventListener("drop", (event) => { event.preventDefault(); reorderHand(Number(event.dataTransfer.getData("text/plain")), Number(button.dataset.index)); }); button.addEventListener("keydown", (event) => { if (event.altKey && (event.key === "ArrowLeft" || event.key === "ArrowRight")) { event.preventDefault(); reorderHand(Number(button.dataset.index), Number(button.dataset.index) + (event.key === "ArrowLeft" ? -1 : 1)); } }); }); $("selection-info").textContent = selected.length ? `${selected.length} selected${validPlay(selected) ? " - legal play" : " - not a legal play"}` : "Drag cards to reorder"; }
function reorderHand(from, to) { if (actionPending || from === to || to < 0 || to >= players[currentPlayer].hand.length) return; const hand = players[currentPlayer].hand; const [card] = hand.splice(from, 1); hand.splice(to, 0, card); selected = selected.map((index) => index === from ? to : from < to && index > from && index <= to ? index - 1 : from > to && index >= to && index < from ? index + 1 : index); render(); }
function toggleCard(index) { if (phase !== "play") return; selected = selected.includes(index) ? selected.filter((item) => item !== index) : [...selected, index]; render(); }
function validPlay(indexes) { const cards = indexes.map((index) => players[currentPlayer].hand[index]); if (!cards.length) return false; if (cards.length === 1) return true; if (cards.every((card) => card.rank === cards[0].rank)) return true; if (cards.length < 3 || !cards.every((card) => card.suit === cards[0].suit)) return false; const values = cards.map(straightValue).sort((a, b) => a - b); return values.every((value, index) => index === 0 || value === values[index - 1] + 1); }
function playHuman() { if (actionPending || !players[currentPlayer].human || !validPlay(selected)) return; actionPending = true; const playedIndexes = [...selected]; const discardRect = $("discard-card").getBoundingClientRect(); const discardCenter = { x: discardRect.left + discardRect.width / 2, y: discardRect.top + discardRect.height / 2 }; document.querySelectorAll(".card-button").forEach((button) => { if (playedIndexes.includes(Number(button.dataset.index))) { const cardRect = button.getBoundingClientRect(); button.style.setProperty("--card-x", `${discardCenter.x - (cardRect.left + cardRect.width / 2)}px`); button.style.setProperty("--card-y", `${discardCenter.y - (cardRect.top + cardRect.height / 2)}px`); button.classList.add("playing"); } }); setTimeout(() => { drawableDiscard = discardPile.length - 1; const cards = playedIndexes.sort((a, b) => b - a).map((index) => players[currentPlayer].hand.splice(index, 1)[0]); discardPile.push(...cards); selected = []; phase = "draw"; actionPending = false; message(`Played ${cards.length === 1 ? "a card" : `${cards.length} cards`}. Draw exactly one card.`); render(); }, 320); }
function recycleDiscard() { if (drawPile.length || discardPile.length < 2) return; const topCard = discardPile.pop(); drawPile = shuffle(discardPile); discardPile = [topCard]; }
function drawFromDeck() { recycleDiscard(); return drawPile.pop(); }
function drawHuman(fromDiscard) { if (phase !== "draw" || !players[currentPlayer].human) return; players[currentPlayer].hand.push(fromDiscard ? discardPile.splice(drawableDiscard, 1)[0] : drawFromDeck()); phase = "play"; advanceTurn(); }
function message(text) { $("table-message").textContent = text; }
function showToast(text) { $("toast").textContent = text; $("toast").classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => $("toast").classList.remove("show"), 2800); }
function callYaniv() { if (phase === "play" && players[currentPlayer].human && handValue(players[currentPlayer].hand) <= 7) scoreRound(currentPlayer); }
function scoreRound(caller) { const table = activePlayers(); const values = table.map((player) => handValue(player.hand)); const lowest = Math.min(...values); const callerSuccessful = values[caller] === lowest && values.filter((value) => value === lowest).length === 1; table.forEach((player, index) => { if (index === caller) player.score += callerSuccessful ? 0 : 30; else if (values[index] !== lowest) player.score += values[index]; }); const loser = table.find((player) => player.score >= 100); nextRoundStarter = caller; handsRevealed = true; phase = "reveal"; gameOver = Boolean(loser); render(); showToast(callerSuccessful ? `${table[caller].name} called Yaniv and scored 0.` : `${table[caller].name} got caught. +30 points.`); if (loser) { const winner = [...table].sort((a, b) => a.score - b.score)[0]; setTimeout(() => showToast(`${winner.name} ${winner.name === "You" ? "win" : "wins"} the table with ${winner.score} points.`), 3000); return; } round++; }
function chooseAIPlay(player) { const matchingRanks = ranks.map((rank) => player.hand.map((card, index) => card.rank === rank ? index : -1).filter((index) => index !== -1)).filter((indexes) => indexes.length > 1).sort((a, b) => b.length - a.length)[0]; if (matchingRanks) return matchingRanks; const suitRuns = suits.map((suit) => player.hand.map((card, index) => ({ card, index })).filter(({ card }) => card.suit === suit.name).sort((a, b) => straightValue(a.card) - straightValue(b.card))).flatMap((cards) => { const runs = []; for (let start = 0; start <= cards.length - 3; start++) { const run = cards.slice(start, start + 3); if (straightValue(run[2].card) === straightValue(run[0].card) + 2) runs.push(run.map(({ index }) => index)); } return runs; }).sort((a, b) => b.reduce((total, index) => total + player.hand[index].value, 0) - a.reduce((total, index) => total + player.hand[index].value, 0))[0]; if (suitRuns) return suitRuns; let highestIndex = 0; player.hand.forEach((card, index) => { if (card.value > player.hand[highestIndex].value) highestIndex = index; }); return [highestIndex]; }
function completesRun(hand, candidate) { const sameSuit = hand.filter((card) => card.suit === candidate.suit).map(straightValue).concat(straightValue(candidate)); return sameSuit.some((first) => sameSuit.includes(first + 1) && sameSuit.includes(first + 2) && [first, first + 1, first + 2].includes(straightValue(candidate))); }
function shouldTakeDiscard(hand, discard, playedCards) { return discard.value <= playedCards.reduce((total, card) => total + card.value, 0) || hand.some((card) => card.rank === discard.rank) || completesRun(hand, discard); }
function advanceTurn() { currentPlayer = (currentPlayer + 1) % playerCount; selected = []; handoffPending = humanCount > 1 && players[currentPlayer].human; render(); if (!handoffPending) setTimeout(runAI, 500); }
function animateAIPlay(callback) { const opponent = document.querySelectorAll(".opponent")[currentPlayer - 1]; const target = $("discard-card"); if (!opponent || !target) { callback(); return; } const sourceRect = opponent.getBoundingClientRect(); const targetRect = target.getBoundingClientRect(); const flight = document.createElement("div"); flight.className = "bot-card-flight"; flight.innerHTML = `<span class="card-back">Y</span>`; flight.style.setProperty("--flight-x", `${targetRect.left + targetRect.width / 2 - (sourceRect.left + sourceRect.width / 2)}px`); flight.style.setProperty("--flight-y", `${targetRect.top + targetRect.height / 2 - (sourceRect.top + sourceRect.height / 2)}px`); flight.style.left = `${sourceRect.left + sourceRect.width / 2 - 45.5}px`; flight.style.top = `${sourceRect.top + sourceRect.height / 2 - 63}px`; document.body.appendChild(flight); flight.addEventListener("animationend", () => { flight.remove(); callback(); }, { once: true }); }
function runAI() { if (gameOver || currentPlayer === 0 && players[currentPlayer].human) return; const player = players[currentPlayer]; if (handValue(player.hand) <= 7) { scoreRound(currentPlayer); return; } const topDiscard = discardPile[discardPile.length - 1]; const cards = chooseAIPlay(player).sort((a, b) => b - a).map((index) => player.hand[index]); animateAIPlay(() => { cards.forEach((card) => player.hand.splice(player.hand.indexOf(card), 1)); discardPile.push(...cards); const fromDiscard = shouldTakeDiscard(player.hand, topDiscard, cards); player.hand.push(fromDiscard ? discardPile.splice(discardPile.length - cards.length - 1, 1)[0] : drawFromDeck()); advanceTurn(); }); }
function dealHand() { if (gameOver) { nextRoundStarter = 0; startRound(); message("A fresh hand has been dealt."); } else if (handsRevealed) { startRound(); message("The deck is being shuffled."); } }
function newGame() { $("setup-dialog").showModal(); }
function startGame() { playerCount = Number($("player-count").value); humanCount = Math.min(Number($("human-count").value), playerCount); players.forEach((player, index) => { player.score = 0; player.human = index < humanCount; }); round = 1; nextRoundStarter = 0; $("setup-dialog").close(); startRound(); message("Your turn. Play a card or call Yaniv."); }
$("human-count").addEventListener("change", () => { $("human-count").value = Math.min(Number($("human-count").value), Number($("player-count").value)); }); $("player-count").addEventListener("change", () => { $("human-count").value = Math.min(Number($("human-count").value), Number($("player-count").value)); }); $("play-top-button").addEventListener("click", playHuman); $("draw-pile").addEventListener("click", () => drawHuman(false)); $("discard-pile").addEventListener("click", () => drawHuman(true)); $("yaniv-button").addEventListener("click", callYaniv); $("new-game-button").addEventListener("click", newGame); $("deal-button").addEventListener("click", dealHand); $("start-game-button").addEventListener("click", startGame); $("rules-button").addEventListener("click", () => $("rules-dialog").showModal()); $("close-rules").addEventListener("click", () => $("rules-dialog").close()); startRound();
